name: Docs

on:
  push:
    branches:
    - master

jobs:
  docs:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
    - name: Install
      run: |
        pip install -e .[dev]
    - name: Build documentation
      run: |
        make html
      working-directory: ./docs
    - name: Commit & push documentation changes
      run: |
        git fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin gh-pages
        git worktree add gh-pages gh-pages
        git -C gh-pages rm -rf .
        cp -recurse docs/_build/html/* gh-pages/
        cd gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation to $GITHUB_SHA" || true
        # The above command will fail if no changes were present, so we ignore
        # the return code.
        git push
