name: Docs

on:
  push:
    branches:
    - main

jobs:
  docs:
    runs-on: windows-2019

    env:
      # XXX https://github.com/scikit-build/scikit-build/issues/740
      SETUPTOOLS_ENABLE_FEATURES: legacy-editable

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
    - name: Install
      run: |
        pip install -e .[dev]
    - name: Build documentation
      run: |
        make html
      working-directory: ./docs
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
